package com.wangxy.base.pojo;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.id
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.name
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.ishot
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    private String ishot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.id
     *
     * @return the value of tb_city.id
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.id
     *
     * @param id the value for tb_city.id
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.name
     *
     * @return the value of tb_city.name
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.name
     *
     * @param name the value for tb_city.name
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.ishot
     *
     * @return the value of tb_city.ishot
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public String getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.ishot
     *
     * @param ishot the value for tb_city.ishot
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public void setIshot(String ishot) {
        this.ishot = ishot == null ? null : ishot.trim();
    }
}