package com.wangxy.base.pojo;

public class UlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.userid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.labelid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    private String labelid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.userid
     *
     * @return the value of tb_ul.userid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.userid
     *
     * @param userid the value for tb_ul.userid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.labelid
     *
     * @return the value of tb_ul.labelid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public String getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.labelid
     *
     * @param labelid the value for tb_ul.labelid
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    public void setLabelid(String labelid) {
        this.labelid = labelid == null ? null : labelid.trim();
    }
}