package com.wangxy.base.mapper;

import com.wangxy.base.pojo.Label;
import com.wangxy.base.pojo.LabelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int countByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int deleteByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    List<Label> selectByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    Label selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int updateByExample(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbggenerated Sun May 26 01:49:50 CST 2019
     */
    int updateByPrimaryKey(Label record);
}